modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL="https://github.com/Mrbysco/ConstructionSticks/issues"
license = "MIT License"

[[mods]]
modId="constructionstick"
version="${file.jarVersion}"
displayName="Construction Sticks"
displayURL="https://github.com/Mrbysco/ConstructionSticks"
authors="Mrbysco, ShyNieke"
credits="ThetaDev for creating Construction Wand"
description='''
Construction Sticks make building easier!

With a Construction Stick you can place multiple blocks (up to 1024) at once, extending your build on the side you're
facing. If that's not enough: you can upgrade your wand with additional cores, allowing you to place a block
behind the block you are facing, conjure blocks in mid air or destroy lots of blocks very fast.
'''
[[dependencies.constructionstick]]
    modId="neoforge"
    type="required"
    versionRange="[21.6.0-beta,)"
    ordering = "NONE"
    side="BOTH"
[[dependencies.constructionstick]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.6,1.22)"
    ordering = "NONE"
    side="BOTH"
